DROP TABLE IF EXISTS tlk_user;

CREATE TABLE tlk_user
(
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         varchar(255) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    role          varchar(32)  NOT NULL,
    status        varchar(32)  NOT NULL,
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now()
);